spring:
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # jpa ??
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  #    defer-datasource-initialization: true


  config:
    import:
      - classpath:/real-application.yml




